services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./bin/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123@
      POSTGRES_DB: tripmate