services:
  app:
    build:
      context: ./
    env_file:
      - .env
    environment:
      spring.profiles.active: prod
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    profiles:
      - "prod"
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tripmate
      MYSQL_DATABASE: tripmate
      MYSQL_USER: tripmate
      MYSQL_PASSWORD: tripmate
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./bin/mysql/data:/var/lib/mysql
      - ./bin/mysql/initdb.d:/docker-entrypoint-initdb.d
    profiles:
      - "prod"
      - "test"
      - "local"
