spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/tripmate
    username: tripmate
    password: tripmate
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v1/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**

integration:
  tourapi:
    service-key: ${TOUR_API_SERVICE_KEY}
    mobile-app: ${TOUR_API_MOBILE_APP}
    mobile-os: ${TOUR_API_MOBILE_OS}
