server:
  port: 8080

spring:
  profiles:
    default: local
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}  # 카카오 REST API 키
            redirect-uri: http://localhost:8080/api/v1/oauth/check
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v1/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**

integration:
  tourapi:
    service-key: ${TOUR_API_SERVICE_KEY}
    mobile-app: ${TOUR_API_MOBILE_APP}
    mobile-os: ${TOUR_API_MOBILE_OS}

jwt:
  key: projectKey-which-is-longer-than-32bits-complete
  access_token_expiration: 604800000 # 7일

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/tripmate
    username: tripmate
    password: tripmate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${MYSQL_DB_URL_DEV}
    username: ${MYSQL_DB_USERNAME_DEV}
    password: ${MYSQL_DB_PASSWORD_DEV}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${MYSQL_DB_URL_PROD}
    username: ${MYSQL_DB_USERNAME_PROD}
    password: ${MYSQL_DB_PASSWORD_PROD}
  jpa:
    hibernate:
      ddl-auto: update
